// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBt92q4Z60Oz9X8GqsTJbqt7GbpQSPeBk',
    appId: '1:810256117032:web:af34535750aee58d3a341d',
    messagingSenderId: '810256117032',
    projectId: 'math-train-game',
    authDomain: 'math-train-game.firebaseapp.com',
    databaseURL: 'https://math-train-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'math-train-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa7VM8buUM3mJCZfr5TFmC8U56cP10fbY',
    appId: '1:810256117032:android:95241f09bf0af9fc3a341d',
    messagingSenderId: '810256117032',
    projectId: 'math-train-game',
    databaseURL: 'https://math-train-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'math-train-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSlHTXmQ17EIv0NA7JSCIz_D6q-bDLJsQ',
    appId: '1:810256117032:ios:7720e2df5c227f313a341d',
    messagingSenderId: '810256117032',
    projectId: 'math-train-game',
    databaseURL: 'https://math-train-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'math-train-game.appspot.com',
    iosBundleId: 'com.example.esimapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSlHTXmQ17EIv0NA7JSCIz_D6q-bDLJsQ',
    appId: '1:810256117032:ios:cd7c45dd0fcc2ea83a341d',
    messagingSenderId: '810256117032',
    projectId: 'math-train-game',
    databaseURL: 'https://math-train-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'math-train-game.appspot.com',
    iosBundleId: 'com.example.esimapp.RunnerTests',
  );
}
